spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          # Original Services
          - id: authorization-server
            uri: lb://AUTHORIZATIONSERVER
            predicates:
              - Path=/authorization/**
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**
          - id: ticket-service
            uri: lb://TICKETSERVICE
            predicates:
              - Path=/ticket/**
          - id: notification-service
            uri: lb://NOTIFICATIONSERVICE
            predicates:
              - Path=/notification/**
          
          # CipherGenix AI Security Platform Services
          - id: vulnerability-detection-service
            uri: lb://CIPHERGENIX-VULNERABILITY-DETECTION-SERVICE
            predicates:
              - Path=/api/v1/vulnerability-detection/**
          - id: model-integrity-service
            uri: lb://CIPHERGENIX-MODEL-INTEGRITY-SERVICE
            predicates:
              - Path=/api/v1/model-integrity/**
          - id: security-engine-service
            uri: lb://CIPHERGENIX-SECURITY-ENGINE-SERVICE
            predicates:
              - Path=/api/v1/security-engine/**
          - id: payment-service
            uri: lb://CIPHERGENIX-PAYMENT-SERVICE
            predicates:
              - Path=/api/v1/payments/**
          - id: ml-model-service
            uri: lb://CIPHERGENIX-ML-MODEL-SERVICE
            predicates:
              - Path=/api/v1/ml-models/**
            #filters:
              #- name:
                #args:
                 #rate-limiter: "#{customRateLimiter}"
                 #key-resolver: "#{customResolver}"

  profiles:
    active: ${ACTIVE_PROFILE:dev}
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${USER_NAME}:${USER_PASSWORD}@localhost:5002/eureka/
server:
  port: ${SERVER_PORT}
jwks:
  uri: ${JWKS_URI}