spring:
  application:
    name: ciphergenix-mvp
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ciphergenix-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ciphergenix.dto"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.ciphergenix: DEBUG
    org.springframework.security: DEBUG

# Security configuration
security:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 24 hours

# AI Detection Engine Configuration
ai:
  detection:
    poisoning:
      contamination-threshold: 0.1
      ensemble-voting-threshold: 0.7
    adversarial:
      confidence-threshold: 0.8
      max-perturbation: 0.1
    monitoring:
      drift-threshold: 0.15
      performance-degradation-threshold: 0.2

# Kafka Topics
kafka:
  topics:
    threat-detection: threat-detection-topic
    model-monitoring: model-monitoring-topic
    security-alerts: security-alerts-topic